[package]
name = "boxing_todo"
version = "0.1.0"
authors = ["lee <lee-dasilva@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json="0.12.4"
